name: hc_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - bottleneck=1.3.8
  - cartopy=0.22.0
  - dask=2024.3.1
  - dask-core=2024.3.1
  - dask-expr=1.0.4
  - jupyterlab=4.1.5
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - netcdf4=1.6.5
  - python=3.12.2
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.19.1
  - python-json-logger=2.0.7
  - python-tzdata=2024.1
  - scipy=1.12.0
  - xarray=2024.2.0